-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. MODELS TABLE
CREATE TABLE IF NOT EXISTS models (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    telegram_id BIGINT UNIQUE NOT NULL,
    username TEXT,
    full_name TEXT,
    bio_short TEXT,
    status TEXT CHECK (status IN ('prospect', 'verifying', 'active', 'rejected', 'paused')) DEFAULT 'prospect',
    credits_balance INTEGER DEFAULT 0,
    is_verified BOOLEAN DEFAULT FALSE,
    verification_video_id TEXT,
    avatar_url TEXT,
    cover_url TEXT,
    followers_count INTEGER DEFAULT 0,
    total_likes INTEGER DEFAULT 0,
    reputation_score DECIMAL(3, 2) DEFAULT 0.00,
    social_links JSONB DEFAULT '{}',
    config_prices JSONB DEFAULT '{}',
    config_persona TEXT,
    config_physique TEXT, -- Stored as comma separated tags or text
    config_payments JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. CLIENTS TABLE
CREATE TABLE IF NOT EXISTS clients (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    telegram_id BIGINT UNIQUE NOT NULL,
    username TEXT,
    country_code TEXT,
    global_reputation INTEGER DEFAULT 100,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. GLOBAL BLACKLIST
CREATE TABLE IF NOT EXISTS global_blacklist (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    telegram_id BIGINT UNIQUE NOT NULL,
    username TEXT,
    reason TEXT,
    severity TEXT CHECK (severity IN ('medium', 'high')),
    added_by UUID REFERENCES models(id), -- Can be NULL for Super Admin additions
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. RELATIONSHIP (Model <-> Client)
CREATE TABLE IF NOT EXISTS model_client_relations (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    model_id UUID REFERENCES models(id),
    client_id UUID REFERENCES clients(id),
    status TEXT CHECK (status IN ('new', 'chatting', 'closing', 'customer', 'archived')),
    total_spend DECIMAL(10, 2) DEFAULT 0.00,
    preferred_payment_method TEXT,
    last_interaction_at TIMESTAMPTZ,
    UNIQUE(model_id, client_id)
);

-- 5. TRANSACTIONS (Credits)
CREATE TABLE IF NOT EXISTS transactions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    model_id UUID REFERENCES models(id),
    client_id UUID REFERENCES clients(id),
    type TEXT CHECK (type IN ('consumption', 'topup', 'bonus')),
    amount INTEGER NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. MESSAGES
CREATE TABLE IF NOT EXISTS messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    relation_id UUID REFERENCES model_client_relations(id),
    sender_type TEXT CHECK (sender_type IN ('user', 'model', 'bot')),
    content TEXT,
    intent TEXT,
    metadata JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. POSTS
CREATE TABLE IF NOT EXISTS posts (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    model_id UUID REFERENCES models(id),
    media_url TEXT NOT NULL,
    media_type TEXT CHECK (media_type IN ('image', 'video')),
    caption TEXT,
    likes_count INTEGER DEFAULT 0,
    comments_count INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. STORIES
CREATE TABLE IF NOT EXISTS stories (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    model_id UUID REFERENCES models(id),
    media_url TEXT NOT NULL,
    media_type TEXT CHECK (media_type IN ('image', 'video')),
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. REVIEWS
CREATE TABLE IF NOT EXISTS reviews (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    model_id UUID REFERENCES models(id),
    client_id UUID REFERENCES clients(id),
    rating INTEGER CHECK (rating >= 1 AND rating <= 5),
    comment TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
