-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Models Table
CREATE TABLE IF NOT EXISTS models (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    telegram_id BIGINT UNIQUE NOT NULL,
    username TEXT,
    full_name TEXT,
    status TEXT CHECK (status IN ('prospect', 'verifying', 'active', 'rejected', 'paused')) DEFAULT 'prospect',
    credits_balance INTEGER DEFAULT 0,
    is_verified BOOLEAN DEFAULT FALSE,
    verification_video_id TEXT,
    config_prices JSONB DEFAULT '{}'::jsonb,
    config_persona TEXT,
    config_physique TEXT,
    config_payments JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    -- Survey / Verification Data
    age INTEGER,
    country TEXT,
    id_photo_id TEXT
);

-- 2. Clients Table (Global)
CREATE TABLE IF NOT EXISTS clients (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    telegram_id BIGINT UNIQUE NOT NULL,
    username TEXT,
    country_code TEXT,
    global_reputation INTEGER DEFAULT 100,
    is_blacklisted BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- New: Credit System
CREATE TABLE IF NOT EXISTS credit_packages (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name TEXT NOT NULL,
    credits INTEGER NOT NULL,
    price INTEGER NOT NULL,
    currency TEXT DEFAULT 'USD',
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS credit_transactions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    model_id UUID REFERENCES models(id) ON DELETE CASCADE,
    amount INTEGER NOT NULL,
    type TEXT CHECK (type IN ('purchase', 'manual', 'admin', 'usage')),
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Model-Client Relations (Many-to-Many logic)
CREATE TABLE IF NOT EXISTS model_client_relations (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    model_id UUID REFERENCES models(id) ON DELETE CASCADE,
    client_id UUID REFERENCES clients(id) ON DELETE CASCADE,
    status TEXT CHECK (status IN ('new', 'chatting', 'closing', 'customer', 'archived')) DEFAULT 'new',
    total_spend DECIMAL(10, 2) DEFAULT 0.00,
    preferred_payment_method TEXT,
    last_interaction_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(model_id, client_id)
);

-- 4. Transactions (Credits)
CREATE TABLE IF NOT EXISTS transactions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    model_id UUID REFERENCES models(id) ON DELETE CASCADE,
    client_id UUID REFERENCES clients(id) ON DELETE SET NULL,
    type TEXT CHECK (type IN ('consumption', 'topup', 'bonus')),
    amount INTEGER NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Blacklist Reports
CREATE TABLE IF NOT EXISTS blacklist_reports (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    reporter_model_id UUID REFERENCES models(id) ON DELETE SET NULL,
    reported_client_id UUID REFERENCES clients(id) ON DELETE CASCADE,
    reason TEXT,
    proof_link TEXT,
    status TEXT CHECK (status IN ('pending', 'approved', 'rejected')) DEFAULT 'pending',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Messages (Chat Memory)
CREATE TABLE IF NOT EXISTS messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    relation_id UUID REFERENCES model_client_relations(id) ON DELETE CASCADE, -- Nullable for Bot<->Model chats
    model_id UUID REFERENCES models(id) ON DELETE CASCADE, -- For Bot<->Model chats context
    sender_type TEXT CHECK (sender_type IN ('user', 'model', 'bot')),
    content TEXT,
    intent TEXT, -- Chat intent/status
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- OpenAI RLS Policies (Optional: Enable if using client-side calls, but we are server-side)
ALTER TABLE models ENABLE ROW LEVEL SECURITY;
ALTER TABLE clients ENABLE ROW LEVEL SECURITY;
-- For now, allowing service_role full access is default. 
-- If 'sb_publishable' key is used, we might need specific policies for public access if intended.
-- Assuming Python script uses Service Role or this logic runs via SQL Editor.
